### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by mtangoo** [angelozerr/tern-outline#1]
First thank you for this plugin. I was thinking of writing one but given my limited knowledge of both advanced JS/NodeJS and tern, I was no where yet ;)

Before I ask the really question please take time to write tern plugin tutorial for beginners

Now my question is will you put it on npm?

**Comment by angelozerr** [comment]
> First thank you for this plugin. I was thinking of writing one but given my limited knowledge of both advanced JS/NodeJS and tern, I was no where yet ;)

Glad this plugin could help you. With which editor do you wish to use? In my case I have done an implementation with CodeMirror (see demos https://github.com/angelozerr/tern-outline/tree/master/demos and Eclipse https://github.com/angelozerr/tern.java/wiki/Tern-Outline-support)

> Before I ask the really question please take time to write tern plugin tutorial for beginners

Perhaps https://github.com/angelozerr/tern-jug could helkp you?

> Now my question is will you put it on npm?

Done https://www.npmjs.com/package/tern-outline

**Comment by mtangoo** [comment]
> With which editor do you wish to use? 

I develop my Own IDE

> Done

Well done and thank you!

**Comment by angelozerr** [comment]
> I develop my Own IDE

If it is based on Java, you could use tern.java core https://github.com/angelozerr/tern.java/tree/master/core

I have a lot of idea, like display controllers of Angular, display ES6 class.

Don't hesitate to create issues with your idea.

**Comment by mtangoo** [comment]
> If it is based on Java

Its is based on C++.

> Don't hesitate to create issues with your idea.

I see, I will do that. Just to add on your list, there you could also add tree for variables defined in function vs global variable ;)

Thanks!
