### ISSUE TITLE
Plugin and View should have the same name Tern-Outline

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern-outline#5]
Plugin and View should have the same name Tern-Outline

**Comment by paulvi** [comment]
Now it is Outline in list
and Tern Explorer as view name

![image](https://cloud.githubusercontent.com/assets/1614482/10038295/8a73e136-61f6-11e5-8d80-07d101b270da.png)

**Comment by angelozerr** [comment]
@paulvi I can change the name "Explorer" -> "Outline", but it means that the view id will change too, are you ok?

**Comment by paulvi** [comment]
yes, I am OK if you do it today. I am going to release tomorrow

![image](https://cloud.githubusercontent.com/assets/1614482/10045543/198b050e-6236-11e5-9827-da61b62792f3.png)

**Comment by angelozerr** [comment]
> yes, I am OK if you do it today. 

I don't know if I will have time to do that today. Perhaps tomorow?

**Comment by paulvi** [comment]
can you then tell me new id value.

I will add both, and Eclipse will take whatever view will be there

ref  https://github.com/angelozerr/tern.java/issues/289

**Comment by angelozerr** [comment]
It will be tern.eclipse.ide.ui.views.TernOutlineView

**Comment by paulvi** [comment]
There is icons to choose for tern outline ;-)

![outline_top_left_corner_tern_half_size](https://cloud.githubusercontent.com/assets/1614482/10063123/dcbb16ca-629c-11e5-908e-f59de59d2fa4.png)

![outline_bottom_left_corner_tern_half_size](https://cloud.githubusercontent.com/assets/1614482/10063136/f6fd1a88-629c-11e5-8e65-e27dab69c3a9.png)

![outline_bottom_right_corner_tern_half_size](https://cloud.githubusercontent.com/assets/1614482/10063137/04f2d4f2-629d-11e5-9633-a3b42ef89d94.png)

**Comment by paulvi** [comment]
![outline_tern_half_size](https://cloud.githubusercontent.com/assets/1614482/10063390/9ecb1290-629f-11e5-8476-8e02b6715ef6.png)
