### ISSUE TITLE
ES6 class methods are not shown as beloning to any function

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern-outline#6]
for a piece

``` js
"use strict";

var HelloWorldServer = class {
    constructor(port, ip){
        this.port = port;
        this.ip = ip;

        var http = require('http');
        this.server = http.createServer(function handler(req, res) {
            res.writeHead(200, {'Content-Type': 'text/plain'});
            res.end('Hello ES6 World\n');
        });
    }

    start(){
        this.server.listen(this.port, this.ip);
    }

    logStatus(){
        console.log('HelloWorldServer is running at http://'+this.ip+':'+this.port);
    }


}

const hws = new HelloWorldServer(1337, '127.0.0.1');
hws.start();
hws.logStatus();
```

![image](https://cloud.githubusercontent.com/assets/1614482/10098297/e6aa6afc-63b2-11e5-8be4-cf48c5c3699f.png)
- [ ] outline does not show that `start()` belongs to HelloWorldServer or its constructor function
- [ ] `logStatus()` is not shown at all

**Comment by angelozerr** [comment]
Yes I know it's related to https://github.com/angelozerr/tern-outline/issues/2 but in this issue I have just displayed class. i would like to display ES6 import.

**Comment by angelozerr** [comment]
So many problems with this issue that I have fixed. Here the result:

![es6outline](https://cloud.githubusercontent.com/assets/1932211/10226099/f39c4444-6865-11e5-9723-86dc9f9a701d.png)

Thanks @paulvi to have playing with ES6 outline.

**Comment by mtangoo** [comment]
:+1:
