### ISSUE TITLE
Prototype methods are returned as anonymous functions

### ISSUE THREAD

**Issue by PhaserEditor2D** [angelozerr/tern-outline#7]
Given this code:

```
function Juan() {
}
Juan.prototype = Object.create(Window.prototype);
Juan.prototype.constructor = Juan;  
Juan.prototype.hello = function () {
};

function Maria() {
}
Maria.prototype = Object.create(Juan.prototype);
Maria.prototype.constructor = Maria;  
Maria.prototype.hola = function () {
};
```

The tern outline plugin shows this tree (taken from Tern IDE):

![image](https://cloud.githubusercontent.com/assets/12187299/11504927/ba0d11ce-9815-11e5-8e62-a1499853832f.png)

I think it is not recognizing the prototype methods, for example in JSDT we get a better result:

![image](https://cloud.githubusercontent.com/assets/12187299/11504989/feabacb4-9815-11e5-9f78-40dd341be644.png)

**Comment by angelozerr** [comment]
Thanks for reporting this issue. I will try to fix when I will find time.

**Comment by angelozerr** [comment]
@boniatillo-com I have fixed this issue, but I use type to do that.

Here a screenshot with your sample, where Windows doesn't exists:

![juan1](https://cloud.githubusercontent.com/assets/1932211/11573056/88f97afa-9a04-11e5-9ad0-1ca108985f54.png)

If you fix it, here the result:

![juan2](https://cloud.githubusercontent.com/assets/1932211/11573066/99ae460a-9a04-11e5-93da-68aea35a175a.png)

Hope you will like  it.

**Comment by PhaserEditor2D** [comment]
Very nice @angelozerr here my screenshot with the fixes. 

![image](https://cloud.githubusercontent.com/assets/12187299/11573875/89fa0d8a-99d6-11e5-870f-d1c03b7813f9.png)

**Comment by angelozerr** [comment]
Cool:) An other advantage to format outline on the server side is that other editor (which ar enot written in Java) can benefit with those kind of fix.

**Comment by PhaserEditor2D** [comment]
Well, a local var is "breaking" it :(

Look this example:

```
function A() {

}

A.prototype = Object.create(null);
A.prototype.constructor = A;
A.prototype.hello = function () {
    var j = 0;
};
```

The result is:

![image](https://cloud.githubusercontent.com/assets/12187299/11574152/e82ffba2-99d7-11e5-9eaa-628973a9941d.png)

The `j` var is out.

> Cool:) An other advantage to format outline on the server side is that other editor (which ar enot 
> written in Java) can benefit with those kind of fix.

Agree.

**Comment by angelozerr** [comment]
@boniatillo-com I have fixed the problem:

![a](https://cloud.githubusercontent.com/assets/1932211/11591079/519e9d38-9a95-11e5-9e51-ca9f85b0ed45.png)

And it was a bad idea to use type, so I have changed and it shoud work, even if type is not good (your sample with Window.prototype).

**Comment by PhaserEditor2D** [comment]
Good, now it works much better.
