### ISSUE TITLE
Support Emberjs

### ISSUE THREAD

**Issue by mtangoo** [angelozerr/tern-outline#9]
If I edit files written in Emberjs tern cannot recognize them and throws error `12:09:40: Error: Failed to Parse Outlines`. I have two requests in this:
1. Can you consider to support Emberjs? 
2. Can you add a way to suppress error (like optional json property)?

Thanks for the good work!

**Comment by angelozerr** [comment]
@mtangoo please add a simple sample (with your github) whch throws this error (i don't know ember and no time to initialize a project). thanks!

> 1. Can you consider to support Emberjs? 

Please add a sample which causes your problem.

> 1. Can you add a way to suppress error (like optional json property)?

Sorry I don't understand?

**Comment by mtangoo** [comment]
> Please add a sample which causes your problem.

Here is a sample model in Ember 

``` js
import DS from 'ember-data';

export default DS.Model.extend({ 
    name: DS.attr(),
    contact: DS.attr(),
    policy: DS.attr(),
    create_time: DS.attr(),
    update_time: DS.attr()
});
```

Another one for component

``` js
import Ember from 'ember';

export default Ember.Component.extend({
});

```

> Sorry I don't understand?

I mean when error happens it will be logged to standard IO. I want to surpress the error

**Comment by angelozerr** [comment]
Have you tested with the last version of outline.js (not from npm but with github project)?

I have none error with your sample? Please share a github project which have a problem.

Please note that If you wish support ember.js, you should create a tern plugin for that to support DS.model.extend for instance.

**Comment by mtangoo** [comment]
@angelozerr 
I use npm package as it is easy to update. I will test the latest git.

I would like to create a plugin but my NodeJs skills lacks a lot.
I have found it hard to do as there are no abc for starters like me ;)

**Comment by angelozerr** [comment]
@mtangoo please share your project, it will be very easy for me to see the errors. 

> I would like to create a plugin but my NodeJs skills lacks a lot.

I was not (and I'm not) a big star with javascript, but I have read and debug ternjs a lot. Perhaps you could start with https://github.com/angelozerr/tern-jug 

In my case I use chrome to debug my plugin

**Comment by mtangoo** [comment]
Hi @angelozerr 
I scan per file not per project and I have already shared the files contents :)
I will have to test latest github code and see if it have errors.

I will check the plugin, hope its plain javascript. Thanks!

**Comment by mtangoo** [comment]
Turned on verbose (tern) and it started working fine. I will reopen if it occurs but for now it looks ok (with latest github sources)

**Comment by mtangoo** [comment]
So I found the real problem.
I have the following `.tern-project` in each project (let say under /home/stef/projects/p1/.config/)

``` json
{
 "ecmaVersion": 6,
 "libs": [
   "browser",
   "jquery"
 ], 
 "plugins": {
   "lint": {},
   "browser-extension": {},
   "jquery-extension": {},
   "outline": {} 
 }}
```

and then I have tern server under completely different directory (let say /home/stef/utilities/tern/)

So I invoke tern using full path and set current working dir to the one in project. I find that I get error:

> Response: 400 No query type 'outline' defined

But If I run with CWD pointing to tern server it just works fine. Do you know how to fix such situation (I know it might be entirely tern issue, but only if you know how to solve it)

**Comment by angelozerr** [comment]
Perhaps it's the same problem than https://github.com/angelozerr/tern-lint/issues/64 ?

**Comment by mtangoo** [comment]
let me check that one!
